modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/Slomaxonical-907/croptopia-chocolaterie-forge/issues" #optional
[[mods]] #mandatory
modId="cacao" #mandatory
version="1.1" #mandatory
displayName="Croptopia's Chocolaterie" #mandatory
logoFile="cacao.png" #optional
credits="" #optional
authors="Slomaxonical" #optional
description='''
This is the forge version of the Croptopia add-on focused on chocolate making.

I tried to make the process as close to real chocolate making as possible:

- roasting the cacao beans
- grinding the roasted nibs to get the cacao mass
- extracting the cacao butter leaving cocoa powder behind, both used in various places...
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cacao]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.cacao]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
    